# merchantonboardingservice/settings_dev.py

from .settings import *

# Add development-specific settings here
"""
Django settings for merchantonboardingservice project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_msjf9d%n$@a0+prr^d#fv+wq09cahhh%e^&a3=6u+=jb0y15+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ROOT_URLCONF = 'merchantonboardingservice.urls'

WSGI_APPLICATION = 'merchantonboardingservice.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


CURRENT_SITE = "http://127.0.0.1:8000/merchantservice"
# CURRENT_SITE = "http://127.0.0.1:8000"

# Always use IPython for shell_plus
SHELL_PLUS = "ipython"

TEST_PHONE_NUMBER = "2348160093332"
TERMII_PHONE_OTP_URL = "https://termii.com/api/sms/send"
TERMII_API_KEY = "TL62g0ZDHddgdbTZLXYosd6834pHqTWB5MG2EkZquN0L7OsoC2QmSYqpfQJAMm"



# [EMAIL]
MAIL_PORT = 465
MAIL_SERVER = "sandbox.smtp.mailtrap.io"
MAIL_USER = "e4ddb8cd5d0f6e"
MAIL_PASS = "7c789e78d8ef2a"



