# Generated by Django 4.2.5 on 2023-09-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='merchant_gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('business_name', models.CharField(max_length=100)),
                ('business_type', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('service', 'Service'), ('restaurant', 'Restaurant'), ('other', 'Other')], max_length=50)),
                ('business_registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('business_start_date', models.DateField(blank=True, null=True)),
                ('business_address', models.TextField()),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit_score', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('social_media_links', models.TextField(blank=True)),
                ('alternate_email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='merchant_logos/')),
                ('notes', models.TextField(blank=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('gallery', models.ManyToManyField(blank=True, to='onboarding.galleryimage')),
            ],
        ),
    ]
