# Generated by Django 4.2.5 on 2023-10-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_remove_merchant_credit_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='credit_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
