# Generated by Django 4.2.5 on 2023-10-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_merchant_credit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$3llG1sBEVu0hOHhdK9AI2y$07UJIY/0AgEO68hrPSIcBWzz5PdwsTJckxPGP9WyN78=', max_length=128),
        ),
    ]
