# Generated by Django 4.2.5 on 2023-10-27 12:36

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_alter_merchant_options_alter_merchant_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacRegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='cac_registration_forms/')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateOfIncorporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='registration_certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='IdUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='id_uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='MemorandumOfAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='moa_documents/')),
            ],
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='alternate_email',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='annual_revenue',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='business_start_date',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='credit_score',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='social_media_links',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='website',
        ),
        migrations.AddField(
            model_name='merchant',
            name='business_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='bvn_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='bvn_verify',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='cac_registration_form',
            field=models.FileField(blank=True, null=True, upload_to='cac_registration_forms/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='certificate_of_incorporation',
            field=models.FileField(blank=True, null=True, upload_to='registration_certificates/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='date_of_birth_verify',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driver_license', "Driver's License"), ('residence_permit', 'Residence Permit'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='enter_otp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='id_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driver_license', "Driver's License"), ('residence_permit', 'Residence Permit'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='id_upload',
            field=models.FileField(blank=True, null=True, upload_to='id_uploads/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='memorandum_of_association',
            field=models.FileField(blank=True, null=True, upload_to='moa_documents/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='number_of_directors',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='merchant',
            name='personal_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='phone_number_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='tin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='business_type',
            field=models.CharField(blank=True, choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('service', 'Service'), ('restaurant', 'Restaurant'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='password',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
