# Generated by Django 4.2.5 on 2023-10-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_cacregistrationform_certificateofincorporation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
