# Generated by Django 4.2.5 on 2023-11-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0008_alter_merchant_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CacRegistrationForm',
        ),
        migrations.DeleteModel(
            name='CertificateOfIncorporation',
        ),
        migrations.DeleteModel(
            name='IdUpload',
        ),
        migrations.DeleteModel(
            name='MemorandumOfAssociation',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='business_name',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='business_details',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='business_registration_number',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='bvn_verified',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='bvn_verify',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='cac_registration_form',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='certificate_of_incorporation',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='date_of_birth_verify',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='enter_otp',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='id_upload',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='memorandum_of_association',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='number_of_directors',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='personal_id',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='phone_number_verified',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='phone_verification_code',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='tin',
        ),
        migrations.AddField(
            model_name='merchant',
            name='other_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
