# Generated by Django 4.2.5 on 2023-11-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_delete_cacregistrationform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='other_name',
            new_name='other_names',
        ),
    ]
