# Generated by Django 4.2.5 on 2023-11-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_rename_other_name_merchant_other_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
