# Generated by Django 4.2.5 on 2023-11-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0011_merchant_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
