# Generated by Django 4.2.5 on 2023-12-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0013_alter_merchant_options_remove_merchant_other_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
