# Generated by Django 4.2.5 on 2024-01-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0014_alter_merchant_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='email_otp_created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='phone_otp_created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
