# Generated by Django 4.2.5 on 2024-01-26 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('onboarding', '0015_otpverification_email_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='merchant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='login_attempts',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
