# Generated by Django 4.2.5 on 2023-09-17 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driver_license', "Driver's License"), ('residence_permit', 'Residence Permit'), ('other', 'Other')], max_length=50)),
                ('document_number', models.CharField(max_length=50)),
                ('document_issue_date', models.DateField()),
                ('document_expiry_date', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('occupation', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('issuing_country', models.CharField(max_length=50)),
                ('current_address', models.TextField()),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('proof_of_address', models.FileField(blank=True, null=True, upload_to='kyc_documents/')),
                ('proof_of_income', models.FileField(blank=True, null=True, upload_to='kyc_documents/')),
                ('notes', models.TextField(blank=True)),
                ('kyc_submission_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_info', to='onboarding.merchant')),
            ],
        ),
    ]
