# Generated by Django 4.2.5 on 2024-01-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kyc', '0002_remove_kyc_marital_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='document_number',
        ),
        migrations.AddField(
            model_name='kyc',
            name='kyc_document',
            field=models.ImageField(
                blank=True,
                help_text='Upload a kyc document with a maximum size of 500x500 pixels',
                null=True,
                upload_to='business/kyc_document/',
                verbose_name='kyc document',
            ),
        ),
    ]
