# Generated by Django 4.2.5 on 2024-01-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kyc', '0003_remove_kyc_document_number_kyc_kyc_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='document_type',
            field=models.CharField(
                choices=[
                    ('passport', 'Passport'),
                    ('voter_card', "Voter's Card"),
                    ('national_id', 'National ID'),
                    ('driver_license', "Driver's License"),
                    ('residence_permit', 'Residence Permit'),
                    ('other', 'Other'),
                ],
                max_length=50,
            ),
        ),
    ]
