# Generated by Django 4.2.5 on 2024-01-28 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kyc', '0004_alter_kyc_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='document_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='document_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='document_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('passport', 'Passport'),
                    ('voter_card', "Voter's Card"),
                    ('national_id', 'National ID'),
                    ('driver_license', "Driver's License"),
                    ('residence_permit', 'Residence Permit'),
                    ('other', 'Other'),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='gender',
            field=models.CharField(
                blank=True,
                choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='issuing_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='merchant',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='kyc_info',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='proof_of_address',
            field=models.FileField(blank=True, null=True, upload_to='business/business_address/'),
        ),
    ]
