# Generated by Django 4.2.5 on 2024-01-28 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kyc', '0005_alter_kyc_current_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='merchant',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name='kyc_info', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
